import { ChartSettings } from '@/types/chart';

export const defaultChartSettings: ChartSettings = {
  chartType: {
    chartType: 'bar_stacked_custom',
    stackSortMode: 'normal',
    gridMode: 'single',
    heightMode: 'auto',
    standardHeight: 400,
    aspectRatio: 16 / 9,
    aggregationMode: 'none',
    sortMode: 'data_sheet',
  },
  controlsFilters: {
    seriesFilter: 'off',
    maxSeriesToShow: 25,
    filterRowsNoData: false,
    controlPosition: 'top_left',
  },
  colors: {
    colorMode: 'by_column',
    palette: 'default',
    extend: true,
    customOverrides: '',
  },
  bars: {
    barHeight: 24,
    barOpacity: 1,
    spacingMain: 12,
    spacingInStack: 0,
    emptyRowSpacing: 24,
    bottomBarPadding: 0,
    emptyRowLine: {
      show: false,
      color: '#cccccc',
      width: 1,
      style: 'solid',
      dashLength: 4,
    },
    outline: false,
    outlineColor: '#ffffff',
    outlineWidth: 1,
    borderRadius: {},
  },
  lineDotsAreas: {
    lineWidth: 0.2,
    lineOpacity: 1,
    lineOutline: false,
    lineCurve: 'catmullRom' as const,
    dashedLines: false,
    dashWidth: 4,
    dashSpaceWidth: 3,
    missingDataMode: 'continue' as const,
    shadeBetweenLines: false,
    dotMode: 'auto' as const,
    dotOpacity: 1,
    dotRadius: 0.25,
    finalDotScale: 100,
    dotHollow: true,
    dotInnerColor: '#ffffff',
    dotInnerOpacity: 100,
  },
  labels: {
    barLabelStyle: 'axis',
    aboveBarPaddingTop: 0,
    aboveBarPaddingRight: 0,
    aboveBarPaddingBottom: 0,
    aboveBarPaddingLeft: 0,
    showDataPointLabels: false,
    dataPointFontSize: 12,
    dataPointFontFamily: 'Inter, sans-serif',
    dataPointFontWeight: 'normal',
    dataPointFontStyle: 'normal',
    dataPointColorMode: 'auto',
    dataPointColor: '#333333',
    dataPointSeriesColors: {},
    dataPointPosition: 'center',
    dataPointCustomMode: 'column',
    dataPointSeriesPositions: {},
    dataPointRowPositions: {},
    dataPointCustomPadding: false,
    dataPointPaddingTop: 0,
    dataPointPaddingRight: 0,
    dataPointPaddingBottom: 0,
    dataPointPaddingLeft: 0,
    outsideLabelPadding: 6,
    fixedLabelAlignment: 'start',
    dataPointLetterSpacing: 0,
    showPercentPrefix: false,
    percentPrefixFontSize: 12,
    percentPrefixFontWeight: 'normal',
    percentPrefixColor: '#333333',
    percentPrefixPadding: 0,
    percentPrefixPaddingTop: 0,
    percentPrefixPaddingBottom: 0,
    percentPrefixPosition: 'right',
    percentPrefixVerticalAlign: 'bottom',
    stackLabelMode: 'none',
    // Line chart label defaults
    showLineLabels: true,
    lineLabelMaxWidth: 4,
    lineLabelSpaceMode: 'auto',
    lineLabelSpaceValue: 80,
    lineLabelOverlap: 'spread',
    lineLabelSpacing: 1.2,
    lineLabelDistance: 0.9,
    lineLabelShowOnly: '',
    lineLabelColor: '#333333',
    lineLabelSize: 0.7,
    lineLabelOutline: '#ffffff',
    lineLabelOutlineWidth: 25,
    lineLabelLineHeight: 1,
    lineLabelMaxLines: 3,
    lineLabelWeight: 'bold',
    lineLabelFontFamily: 'Inter, sans-serif',
    lineLabelFontStyle: 'normal',
    lineLabelColorMode: 'fixed',
    lineLabelSeriesColors: {},
    connectorLineMode: 'auto',
    connectorLineStyle: 'straight',
    connectorLineColor: '#999999',
    connectorLineWidth: 0,
    connectorLineLength: 0,
    connectorLinePadding: 0.25,
    dataPointShowMode: 'all',
    dataPointHideOverlapping: false,
    dataPointCenterOnDot: false,
    dataPointTextColorMode: 'auto',
    dataPointTextColorFixed: '#333333',
    dataPointLabelContent: 'auto',
    dataPointSizeMode: 'fixed',
    dataPointSizeFixed: 1.2,
    dataPointOutlineOn: true,
    dataPointOutlineSize: 3,
    lineDataPointColorMode: 'auto',
    lineDataPointColorFixed: '#333333',
    lineDataPointSeriesColors: {},
    lineDataPointColorCustomMode: 'column',
    lineDataPointRowColors: {},
    lineDataPointPosition: 'above',
    lineDataPointCustomMode: 'column',
    lineDataPointSeriesPositions: {},
    lineDataPointRowPositions: {},
    dataPointRowPaddingEnabled: {},
    dataPointRowPadding: {},
  },
  xAxis: {
    position: 'bottom',
    scaleType: 'linear',
    min: '',
    max: '',
    flipAxis: false,
    titleType: 'auto',
    titleText: '',
    titleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 12, fontWeight: 'normal', color: '#666666' },
    showTitleStyling: false,
    tickPosition: 'default',
    tickStyling: { fontFamily: 'Inter, sans-serif', fontSize: 11, fontWeight: 'normal', color: '#666666' },
    showTickStyling: false,
    tickPadding: 0,
    tickAngle: 0,
    ticksToShowMode: 'auto',
    ticksToShowNumber: 5,
    tickStep: 10,
    tickLabelCountMode: 'all',
    tickLabelCount: 0,
    hiddenTickLabels: [],
    firstLabelPadding: 0,
    firstTickPadding: 0,
    lastLabelPadding: 0,
    lastTickPadding: 0,
    labelAxisPadding: 0,
    startPadding: 0,
    endPadding: 0,
    tickMarks: { show: true, position: 'outside', length: 6, width: 1, color: '#666666' },
    axisLine: { show: true, width: 1, color: '#666666' },
    zeroLine: { show: true, width: 1, color: '#666666' },
    zeroLineExtendTop: 0,
    zeroLineExtendBottom: 0,
    gridlines: true,
    showZeroGridline: true,
    gridlineStyling: { color: '#e5e5e5', width: 1, dashArray: 0 },
    showGridlineStyling: false,
  },
  yAxis: {
    position: 'left',
    scaleType: 'linear',
    min: '',
    max: '',
    titleType: 'auto',
    titleText: '',
    titleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 12, fontWeight: 'normal', color: '#666666' },
    showTitleStyling: false,
    tickPosition: 'default',
    tickStyling: { fontFamily: 'Inter, sans-serif', fontSize: 11, fontWeight: 'normal', color: '#666666' },
    showTickStyling: false,
    tickPadding: 0,
    spaceMode: 'auto',
    spaceModeValue: 120,
    fixedMaxLines: 0,
    fixedEllipsis: true,
    axisLine: { show: true, width: 1, color: '#666666' },
    gridlines: false,
    gridlineStyling: { color: '#e5e5e5', width: 1, dashArray: 0 },
    showGridlineStyling: false,
    // Line chart Y axis defaults
    flipAxis: false,
    configureDefaultMinMax: false,
    axisTitlePosition: 'side',
    labelWeight: 'normal',
    labelMaxLines: 1,
    labelLineHeight: 0.5,
    ticksToShowMode: 'auto',
    ticksToShowNumber: 6,
    customTickStart: 0,
    customTickEnd: 0,
    edgePadding: 10,
    gridlineStyle: 'solid',
    gridlineBetweenCategories: false,
    labelTextAlign: 'end',
    labelLetterSpacing: 0,
    labelMargin: 0,
  },
  plotBackground: {
    backgroundColor: '#ffffff',
    backgroundOpacity: 100,
    border: false,
    borderColor: '#cccccc',
    borderWidth: 1,
  },
  numberFormatting: {
    decimalPlaces: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    prefix: '',
    suffix: '',
    showTrailingZeros: true,
    roundDecimal: true,
    xAxisCustomDecimals: false,
    xAxisDecimalPlaces: 0,
    yAxisCustomDecimals: false,
    yAxisDecimalPlaces: 0,
    infoCustomDecimals: false,
    infoDecimalPlaces: 2,
    infoPrefix: '',
    infoSuffix: '',
    infoThousandsSeparator: undefined,
    infoDecimalSeparator: undefined,
  },
  legend: {
    show: true,
    clickToFilter: 'off',
    alignment: 'inline',
    titleWeight: 'bold',
    textWeight: 'normal',
    textStyle: 'normal',
    fontFamily: 'Inter, sans-serif',
    color: '#333333',
    size: 12,
    marginTop: 0,
    titleText: '',
    swatchWidth: 15,
    swatchHeight: 15,
    swatchRoundness: 0,
    swatchPadding: 6,
    outline: false,
    customOrder: '',
    maxWidth: 100,
    orientation: 'horizontal',
    position: 'below',
    overlayX: 10,
    overlayY: 10,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    dataColorsHeader: 'auto',
    wrapMode: 'auto',
    fixedItemsPerRow: 3,
    rowGap: 4,
  },
  popupsPanels: {
    showPopup: true,
    popupContent: '{{column_name}}: {{value}}',
    popupStyle: 'light',
  },
  annotations: {
    annotations: [],
  },
  animations: {
    enabled: true,
    duration: 800,
    type: 'gradual',
  },
  layout: {
    maxWidth: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    backgroundColor: '#ffffff',
    backgroundOpacity: 100,
  },
  question: {
    text: '',
    textDefaults: { fontFamily: 'Inter, sans-serif', fontSize: 18, color: '#333333', lineHeight: 1.3 },
    subtext: '',
    subtextDefaults: { fontFamily: 'Inter, sans-serif', fontSize: 14, color: '#666666', lineHeight: 1.4 },
    position: 'above',
    alignment: 'left',
    paddingTop: 8,
    paddingRight: 16,
    paddingBottom: 8,
    paddingLeft: 16,
    subtextPaddingTop: 4,
    subtextPaddingRight: 16,
    subtextPaddingBottom: 8,
    subtextPaddingLeft: 16,
    accentLine: {
      show: false,
      width: 4,
      color: '#3b82f6',
      borderRadius: 2,
      paddingTop: 0,
      paddingRight: 8,
      paddingBottom: 0,
      paddingLeft: 0,
    },
  },
  header: {
    alignment: 'left',
    title: '',
    titleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 22, fontWeight: 'bold', color: '#333333', lineHeight: 1.3 },
    subtitle: '',
    subtitleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 16, fontWeight: 'normal', color: '#666666', lineHeight: 1.4 },
    text: '',
    textStyling: { fontFamily: 'Inter, sans-serif', fontSize: 14, fontWeight: 'normal', color: '#888888', lineHeight: 1.4 },
    border: 'none',
  },
  footer: {
    alignment: 'left',
    size: 11,
    color: '#888888',
    advancedStyles: false,
    textStyling: { fontFamily: 'Inter, sans-serif', fontSize: 11, fontWeight: 'normal', color: '#888888', lineHeight: 1.4 },
    showTextStyling: false,
    sourceName: '',
    sourceUrl: '',
    multipleSources: false,
    sourceLabel: 'Source',
    notePrimary: '',
    noteSecondary: '',
    logoUrl: '',
    border: 'none',
  },
  accessibility: {
    alternativeDescription: '',
    altText: '',
  },
  barRowBorders: {
    show: false,
    mode: 'all' as const,
    color: '#e0e0e0',
    width: 1,
    style: 'solid' as const,
    dashLength: 4,
    alignment: 'center' as const,
    customRows: [],
  },
  connectorBorder: {
    show: false,
    color: '#cccccc',
    width: 1,
    style: 'solid' as const,
    length: 20,
    paddingBar: 4,
    paddingLabel: 4,
    alignment: 'center' as const,
  },
  customPrefix: {
    show: false,
    text: '%',
    position: 'right' as const,
    fontSize: 12,
    fontWeight: 'normal' as const,
    color: '#333333',
    padding: 0,
    paddingTop: 0,
    paddingBottom: 0,
    verticalAlign: 'bottom' as const,
  },
  infoColumn: {
    show: false,
    position: 'right' as const,
    verticalAlignment: 'center' as const,
    verticalPadding: 0,
    fontSize: 12,
    fontFamily: 'Inter, sans-serif',
    fontWeight: 'normal' as const,
    color: '#333333',
    letterSpacing: 0,
    padding: 8,
    customPadding: false,
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
    dataType: 'number' as const,
    perRowColors: {},
    perRowFontSizes: {},
    perRowFontFamilies: {},
    perRowFontWeights: {},
    perRowLetterSpacings: {},
    perRowPaddings: {},
    icon: {
      show: false,
      size: 14,
      borderWidth: 2,
      defaultColor: '#666666',
      perRowColors: {},
      perRowIconNames: {},
      iconName: 'circle',
      customPadding: false,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    borderLeft: { show: false, color: '#e0e0e0', width: 1, style: 'solid' as const, padding: 0 },
    borderRight: { show: false, color: '#e0e0e0', width: 1, style: 'solid' as const, padding: 0 },
  },
  barBackground: {
    show: false,
    color: '#f0f0f0',
    opacity: 0.3,
  },
};

export const defaultData = [
  { label: 'Australia', 'Series 1': 28, 'Series 2': 15, 'Series 3': 12 },
  { label: 'Brazil', 'Series 1': 22, 'Series 2': 18, 'Series 3': 25 },
  { label: 'Canada', 'Series 1': 35, 'Series 2': 20, 'Series 3': 8 },
  { label: 'France', 'Series 1': 18, 'Series 2': 30, 'Series 3': 16 },
  { label: 'Germany', 'Series 1': 42, 'Series 2': 12, 'Series 3': 22 },
  { label: 'India', 'Series 1': 15, 'Series 2': 35, 'Series 3': 28 },
  { label: 'Japan', 'Series 1': 30, 'Series 2': 25, 'Series 3': 18 },
];

export const defaultColumnMapping = {
  labels: 'label',
  values: ['Series 1', 'Series 2', 'Series 3'],
};
