import { ChartSettings } from '@/types/chart';

export const defaultChartSettings: ChartSettings = {
  chartType: {
    chartType: 'bar_stacked_custom',
    stackSortMode: 'normal',
    gridMode: 'single',
    heightMode: 'auto',
    standardHeight: 400,
    aspectRatio: 16 / 9,
    aggregationMode: 'none',
    sortMode: 'data_sheet',
  },
  controlsFilters: {
    seriesFilter: 'off',
    maxSeriesToShow: 25,
    filterRowsNoData: false,
    controlPosition: 'top_left',
  },
  colors: {
    colorMode: 'by_column',
    palette: 'default',
    extend: true,
    customOverrides: '',
  },
  bars: {
    barHeight: 24,
    barOpacity: 1,
    spacingMain: 12,
    spacingInStack: 0,
    emptyRowSpacing: 24,
    emptyRowCustomPadding: false,
    emptyRowPaddingH: 0,
    emptyRowPaddingV: 0,
    bottomBarPadding: 0,
    emptyRowLine: {
      show: false,
      color: '#cccccc',
      width: 1,
      style: 'solid',
      dashLength: 4,
    },
    outline: false,
    outlineColor: '#ffffff',
    outlineWidth: 1,
    borderRadius: {},
    proportionalSize: false,
    proportionalSizeValue: 100,
  },
  columns: {
    mode: 'grouped',
    columnWidth: 0.8,
    groupSpacing: 0.05,
    maxColumnWidth: 0,
    minColumnHeight: 0,
    cornerRadius: 0,
    opacity: 1,
    outline: false,
    outlineColor: '#ffffff',
    outlineWidth: 1,
    showValues: false,
    valuePosition: 'above',
    valueFontFamily: 'Inter, sans-serif',
    valueFontSize: 12,
    valueFontWeight: 'normal',
    valueColorMode: 'auto',
    valueColor: '#333333',
  },
  lineDotsAreas: {
    lineWidth: 0.2,
    lineOpacity: 1,
    lineOutline: false,
    lineCurve: 'catmullRom' as const,
    dashedLines: false,
    dashWidth: 4,
    dashSpaceWidth: 3,
    missingDataMode: 'continue' as const,
    shadeBetweenLines: false,
    dotMode: 'auto' as const,
    dotOpacity: 1,
    dotRadius: 0.25,
    finalDotScale: 100,
    dotHollow: true,
    dotInnerColor: '#ffffff',
    dotInnerOpacity: 100,
  },
  labels: {
    barLabelStyle: 'axis',
    aboveBarPaddingTop: 0,
    aboveBarPaddingRight: 0,
    aboveBarPaddingBottom: 0,
    aboveBarPaddingLeft: 0,
    barGroupVerticalOffset: 0,
    showDataPointLabels: false,
    dataPointFontSize: 12,
    dataPointFontFamily: 'Inter, sans-serif',
    dataPointFontWeight: 'normal',
    dataPointFontStyle: 'normal',
    dataPointColorMode: 'auto',
    dataPointColor: '#333333',
    dataPointAutoWhitePref: true,
    dataPointAutoWhiteStrength: 60,
    dataPointSeriesColors: {},
    dataPointColorCustomMode: 'column',
    dataPointRowColors: {},
    dataPointPosition: 'center',
    dataPointCustomMode: 'column',
    dataPointSeriesPositions: {},
    dataPointRowPositions: {},
    showZeroValues: false,
    dataPointCustomPadding: false,
    dataPointPaddingTop: 0,
    dataPointPaddingRight: 0,
    dataPointPaddingBottom: 0,
    dataPointPaddingLeft: 0,
    dataPointPaddingH: 0,
    dataPointPaddingV: 0,
    barDataPointRowSeriesPadding: {},
    outsideLabelPadding: 6,
    fixedLabelAlignment: 'start',
    dataPointLetterSpacing: 0,
    showPercentPrefix: false,
    percentPrefixFontSize: 12,
    percentPrefixFontWeight: 'normal',
    percentPrefixColor: '#333333',
    percentPrefixPadding: 0,
    percentPrefixPaddingTop: 0,
    percentPrefixPaddingBottom: 0,
    percentPrefixPosition: 'right',
    percentPrefixVerticalAlign: 'bottom',
    stackLabelMode: 'none',
    // Line chart label defaults
    showLineLabels: true,
    lineLabelMaxWidth: 4,
    lineLabelSpaceMode: 'auto',
    lineLabelSpaceValue: 80,
    lineLabelOverlap: 'spread',
    lineLabelSpacing: 1.2,
    lineLabelDistance: 0.9,
    lineLabelDistanceV: 0,
    lineLabelShowOnly: '',
    lineLabelColor: '#333333',
    lineLabelSize: 12,
    lineLabelOutline: '#ffffff',
    lineLabelOutlineWidth: 25,
    lineLabelLineHeight: 1,
    lineLabelMaxLines: 3,
    lineLabelWeight: 'bold',
    lineLabelFontFamily: 'Inter, sans-serif',
    lineLabelFontStyle: 'normal',
    lineLabelColorMode: 'fixed',
    lineLabelSeriesColors: {},
    lineLabelMatchLineColor: false,
    connectorLineMode: 'auto',
    connectorLineStyle: 'straight',
    connectorLineColor: '#999999',
    connectorLineWidth: 0,
    connectorLineLength: 0,
    connectorLinePadding: 0.25,
    dataPointShowMode: 'all',
    dataPointHideOverlapping: false,
    dataPointCenterOnDot: false,
    dataPointTextColorMode: 'auto',
    dataPointTextColorFixed: '#333333',
    dataPointLabelContent: 'auto',
    dataPointSizeMode: 'fixed',
    dataPointSizeFixed: 1.2,
    dataPointOutlineOn: true,
    dataPointOutlineSize: 3,
    lineDataPointMatchLineColor: false,
    lineDataPointColorMode: 'auto',
    lineDataPointColorFixed: '#333333',
    lineDataPointSeriesColors: {},
    lineDataPointColorCustomMode: 'column',
    lineDataPointRowColors: {},
    lineDataPointPosition: 'above',
    lineDataPointCustomMode: 'column',
    lineDataPointSeriesPositions: {},
    lineDataPointRowPositions: {},
    dataPointRowPaddingEnabled: {},
    dataPointRowPadding: {},
    gridTitlePosition: 'top',
    gridTitleFontFamily: 'Inter, sans-serif',
    gridTitleFontSize: 14,
    gridTitleFontWeight: '600',
    gridTitleFontStyle: 'normal',
    gridTitleColor: '#333333',
    gridTitlePaddingH: 0,
    gridTitlePaddingV: 0,
    gridTitleAlignment: 'center',
    gridTitlePerSeriesOverrides: {},
  },
  xAxis: {
    position: 'bottom',
    scaleType: 'linear',
    min: '',
    max: '',
    flipAxis: false,
    titleType: 'auto',
    titleText: '',
    titleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 12, fontWeight: 'normal', color: '#666666' },
    showTitleStyling: false,
    tickPosition: 'default',
    tickStyling: { fontFamily: 'Inter, sans-serif', fontSize: 11, fontWeight: 'normal', color: '#666666' },
    showTickStyling: false,
    tickPadding: 0,
    tickAngle: 0,
    ticksToShowMode: 'auto',
    ticksToShowNumber: 5,
    tickStep: 10,
    tickLabelCountMode: 'all',
    tickLabelCount: 0,
    hiddenTickLabels: [],
    firstLabelPadding: 0,
    firstTickPadding: 0,
    lastLabelPadding: 0,
    lastTickPadding: 0,
    labelAxisPadding: 0,
    labelAxisPaddingH: 0,
    startPadding: 0,
    endPadding: 0,
    tickMarks: { show: true, position: 'outside', length: 6, width: 1, color: '#666666' },
    axisLine: { show: true, width: 1, color: '#666666' },
    zeroLine: { show: true, width: 1, color: '#666666' },
    zeroLineExtendTop: 0,
    zeroLineExtendBottom: 0,
    gridlines: true,
    showZeroGridline: true,
    gridlineStyling: { color: '#e5e5e5', width: 1, dashArray: 0 },
    showGridlineStyling: false,
  },
  yAxis: {
    position: 'left',
    scaleType: 'linear',
    min: '',
    max: '',
    titleType: 'auto',
    titleText: '',
    titleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 12, fontWeight: 'normal', color: '#666666' },
    showTitleStyling: false,
    tickPosition: 'default',
    tickStyling: { fontFamily: 'Inter, sans-serif', fontSize: 11, fontWeight: 'normal', color: '#666666' },
    showTickStyling: false,
    tickPadding: 0,
    spaceMode: 'auto',
    spaceModeValue: 120,
    spaceModeRatio: 50,
    spaceModeCollapse: true,
    fixedMaxLines: 0,
    fixedEllipsis: true,
    axisLine: { show: true, width: 1, color: '#666666' },
    gridlines: false,
    gridlineStyling: { color: '#e5e5e5', width: 1, dashArray: 0 },
    showGridlineStyling: false,
    // Line chart Y axis defaults
    flipAxis: false,
    configureDefaultMinMax: false,
    axisTitlePosition: 'side',
    labelWeight: 'normal',
    labelMaxLines: 1,
    labelLineHeight: 0.5,
    ticksToShowMode: 'auto',
    ticksToShowNumber: 6,
    customTickStart: 0,
    customTickEnd: 0,
    edgePadding: 10,
    gridlineStyle: 'solid',
    gridlineLengthExtend: 0,
    gridlinePaddingH: 0,
    gridlinePaddingV: 0,
    gridlineBetweenCategories: false,
    labelTextAlign: 'end',
    labelLetterSpacing: 0,
    labelMargin: 0,
    labelPaddingH: 0,
    labelPaddingV: 0,
  },
  plotBackground: {
    backgroundColor: '#ffffff',
    backgroundOpacity: 100,
    border: false,
    borderColor: '#cccccc',
    borderWidth: 1,
  },
  numberFormatting: {
    decimalPlaces: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    prefix: '',
    suffix: '',
    showTrailingZeros: true,
    roundDecimal: true,
    xAxisCustomDecimals: false,
    xAxisDecimalPlaces: 0,
    yAxisCustomDecimals: false,
    yAxisDecimalPlaces: 0,
    infoCustomDecimals: false,
    infoDecimalPlaces: 2,
    infoPrefix: '',
    infoSuffix: '',
    infoThousandsSeparator: undefined,
    infoDecimalSeparator: undefined,
  },
  legend: {
    show: true,
    clickToFilter: 'off',
    alignment: 'inline',
    titleWeight: 'bold',
    textWeight: 'normal',
    textStyle: 'normal',
    fontFamily: 'Inter, sans-serif',
    color: '#333333',
    size: 12,
    marginTop: 0,
    titleText: '',
    swatchWidth: 15,
    swatchHeight: 15,
    swatchRoundness: 0,
    swatchPadding: 6,
    outline: false,
    customOrder: '',
    maxWidth: 100,
    orientation: 'horizontal',
    position: 'below',
    overlayX: 10,
    overlayY: 10,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    dataColorsHeader: 'auto',
    wrapMode: 'auto',
    fixedItemsPerRow: 3,
    rowGap: 4,
  },
  popupsPanels: {
    showPopup: true,
    popupContent: '{{column_name}}: {{value}}',
    popupStyle: 'light',
  },
  annotations: {
    annotations: [],
  },
  animations: {
    enabled: true,
    duration: 800,
    type: 'gradual',
  },
  layout: {
    maxWidth: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    backgroundColor: '#ffffff',
    backgroundOpacity: 100,
    outerPaddingTop: 0,
    outerPaddingRight: 0,
    outerPaddingBottom: 0,
    outerPaddingLeft: 0,
  },
  question: {
    text: '',
    textDefaults: { fontFamily: 'Inter, sans-serif', fontSize: 18, color: '#333333', lineHeight: 1.3 },
    subtext: '',
    subtextDefaults: { fontFamily: 'Inter, sans-serif', fontSize: 14, color: '#666666', lineHeight: 1.4 },
    position: 'above',
    alignment: 'left',
    paddingTop: 8,
    paddingRight: 16,
    paddingBottom: 8,
    paddingLeft: 16,
    subtextPaddingTop: 4,
    subtextPaddingRight: 16,
    subtextPaddingBottom: 8,
    subtextPaddingLeft: 16,
    accentLine: {
      show: false,
      width: 4,
      color: '#3b82f6',
      borderRadius: 2,
      paddingTop: 0,
      paddingRight: 8,
      paddingBottom: 0,
      paddingLeft: 0,
    },
  },
  header: {
    alignment: 'left',
    title: '',
    titleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 22, fontWeight: 'bold', color: '#333333', lineHeight: 1.3 },
    subtitle: '',
    subtitleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 16, fontWeight: 'normal', color: '#666666', lineHeight: 1.4 },
    text: '',
    textStyling: { fontFamily: 'Inter, sans-serif', fontSize: 14, fontWeight: 'normal', color: '#888888', lineHeight: 1.4 },
    border: 'none',
  },
  footer: {
    alignment: 'left',
    size: 11,
    color: '#888888',
    advancedStyles: false,
    textStyling: { fontFamily: 'Inter, sans-serif', fontSize: 11, fontWeight: 'normal', color: '#888888', lineHeight: 1.4 },
    showTextStyling: false,
    sourceName: '',
    sourceUrl: '',
    multipleSources: false,
    sourceLabel: 'Source',
    notePrimary: '',
    noteSecondary: '',
    logoUrl: '',
    border: 'none',
  },
  accessibility: {
    alternativeDescription: '',
    altText: '',
  },
  barRowBorders: {
    show: false,
    mode: 'all' as const,
    color: '#e0e0e0',
    width: 1,
    style: 'solid' as const,
    dashLength: 4,
    alignment: 'center' as const,
    customRows: [],
  },
  connectorBorder: {
    show: false,
    color: '#cccccc',
    width: 1,
    style: 'solid' as const,
    length: 20,
    paddingBar: 4,
    paddingLabel: 4,
    alignment: 'center' as const,
  },
  customPrefix: {
    show: false,
    text: '%',
    position: 'right' as const,
    fontSize: 12,
    fontWeight: 'normal' as const,
    color: '#333333',
    padding: 0,
    paddingTop: 0,
    paddingBottom: 0,
    verticalAlign: 'bottom' as const,
  },
  infoColumn: {
    show: false,
    position: 'right' as const,
    verticalAlignment: 'center' as const,
    verticalPadding: 0,
    fontSize: 12,
    fontFamily: 'Inter, sans-serif',
    fontWeight: 'normal' as const,
    fontStyle: 'normal' as const,
    color: '#333333',
    letterSpacing: 0,
    padding: 8,
    customPadding: false,
    paddingVertical: 0,
    paddingHorizontal: 8,
    dataType: 'number' as const,
    perRowColors: {},
    perRowFontSizes: {},
    perRowFontFamilies: {},
    perRowFontWeights: {},
    perRowLetterSpacings: {},
    perRowPaddings: {},
    icon: {
      show: false,
      size: 14,
      borderWidth: 2,
      defaultColor: '#666666',
      perRowColors: {},
      perRowIconNames: {},
      iconName: 'circle',
      customPadding: false,
      paddingVertical: 0,
      paddingHorizontal: 0,
    },
    borderLeft: { show: false, color: '#e0e0e0', width: 1, style: 'solid' as const, padding: 0 },
    borderRight: { show: false, color: '#e0e0e0', width: 1, style: 'solid' as const, padding: 0 },
    background: {
      show: false,
      color: '#f3f4f6',
      paddingTop: 4,
      paddingBottom: 4,
      paddingLeft: 8,
      paddingRight: 8,
      borderRadius: 6,
      perRowColors: {},
    },
  },
  barBackground: {
    show: false,
    color: '#f0f0f0',
    opacity: 0.3,
  },
  rowImages: {
    show: false,
    imagePosition: 'right' as const,
    defaultUrl: '',
    defaultWidth: 24,
    defaultHeight: 24,
    borderRadius: 0,
    customPadding: false,
    paddingTop: 0,
    paddingRight: 4,
    paddingBottom: 0,
    paddingLeft: 0,
    customImageOverrides: '',
    resolvedImageOverrides: {},
    perRowUrls: {},
    perRowWidths: {},
    perRowHeights: {},
  },
  electionBar: {
    barHeight: 48,
    spacingBetweenSegments: 2,
    barOpacity: 1,
    manualPlotWidth: false,
    manualPlotWidthValue: 500,
    outline: false,
    outlineColor: '#ffffff',
    outlineWidth: 1,
    showDataPoints: true,
    defaultDataPointStyle: {
      fontSize: 24,
      fontFamily: 'Inter, sans-serif',
      fontWeight: 'bold' as const,
      fontStyle: 'normal' as const,
      color: '#ffffff',
      letterSpacing: 0,
    },
    perRowDataPointStyles: {},
    perRowDataPointAlign: {},
    dataPointPaddingTop: 0,
    dataPointPaddingRight: 4,
    dataPointPaddingBottom: 0,
    dataPointPaddingLeft: 4,
    perRowDataPointPadding: {},
    defaultPrefix: {
      show: true,
      text: '%',
      position: 'left' as const,
      fontSize: 14,
      fontWeight: 'normal' as const,
      color: '#ffffff',
      padding: 0,
      paddingTop: 0,
      paddingBottom: 0,
      verticalAlign: 'center' as const,
    },
    perRowPrefixSettings: {},
    defaultLabelPosition: 'above_bar' as const,
    defaultLabelAlign: 'left' as const,
    defaultLabelStyle: {
      fontSize: 14,
      fontFamily: 'Inter, sans-serif',
      fontWeight: 'bold' as const,
      fontStyle: 'normal' as const,
      color: '#333333',
      letterSpacing: 0,
    },
    perRowLabelPosition: {},
    perRowLabelAlign: {},
    perRowLabelStyles: {},
    legendVisibleRows: {},
    showDataPointsInfo: false,
    defaultInfoStyle: {
      fontSize: 11,
      fontFamily: 'Inter, sans-serif',
      fontWeight: 'normal' as const,
      fontStyle: 'normal' as const,
      color: '#666666',
      letterSpacing: 0,
    },
    perRowInfoVisible: {},
    perRowInfoStyles: {},
    infoPaddingTop: 4,
    defaultNumberFormat: {
      decimalPlaces: 0,
      thousandsSeparator: ',' as const,
      decimalSeparator: ',' as const,
      prefix: '',
      suffix: '',
      showTrailingZeros: true,
    },
    perRowNumberFormat: {},
    defaultInfoNumberFormat: {
      decimalPlaces: 2,
      thousandsSeparator: ',' as const,
      decimalSeparator: ',' as const,
      prefix: '%',
      suffix: '',
      showTrailingZeros: true,
    },
    perRowInfoNumberFormat: {},
    leftImage: {
      show: false,
      defaultSettings: {
        show: true,
        url: '',
        width: 60,
        height: 60,
        borderRadius: 0,
        paddingTop: 0,
        paddingRight: 8,
        paddingBottom: 0,
        paddingLeft: 0,
      },
      perRowSettings: {},
    },
    rightImage: {
      show: false,
      defaultSettings: {
        show: true,
        url: '',
        width: 60,
        height: 60,
        borderRadius: 0,
        paddingTop: 0,
        paddingRight: 0,
        paddingBottom: 0,
        paddingLeft: 8,
      },
      perRowSettings: {},
    },
    differenceBar: {
      show: false,
      source: 'info' as const,
      height: 44,
      backgroundColor: '#fde8ec',
      cornerRadius: 0,
      marginTop: 4,
      template: '{leader} +{value}',
      matchLeaderColor: true,
      color: '#cc0033',
      fontFamily: 'Inter, sans-serif',
      fontSize: 22,
      fontWeight: 'bold' as const,
      fontStyle: 'normal' as const,
      align: 'center' as const,
      letterSpacing: 0,
      numberFormat: {
        decimalPlaces: 2,
        thousandsSeparator: '.' as const,
        decimalSeparator: ',' as const,
        prefix: '',
        suffix: '',
        showTrailingZeros: true,
      },
    },
  },
  resultBar: {
    barHeight: 110,
    segmentSpacing: 2,
    cornerRadius: 0,
    barOpacity: 1,
    outline: false,
    outlineColor: '#ffffff',
    outlineWidth: 1,
    manualPlotWidth: false,
    manualPlotWidthValue: 800,
    valuePosition: 'auto' as const,
    valueFontFamily: 'Inter, sans-serif',
    valueFontSize: 48,
    valueFontWeight: 'bold' as const,
    valueColorMode: 'auto' as const,
    valueColor: '#ffffff',
    valueContrastThreshold: 50,
    valueLetterSpacing: 0,
    valueAlignEdges: true,
    valuePaddingX: 20,
    prefixShow: true,
    prefixText: '%',
    prefixPosition: 'left' as const,
    prefixFontSize: 24,
    prefixVAlign: 'center' as const,
    prefixPadding: 0,
    numberFormat: { decimalPlaces: 2, thousandsSeparator: '.' as const, decimalSeparator: ',' as const, prefix: '', suffix: '', showTrailingZeros: true },
    belowLineColor: '#9ca3af',
    belowLineWidth: 1,
    belowLineLength: 14,
    belowGap: 6,
    belowFontSize: 18,
    belowFontWeight: 'bold' as const,
    belowColorMode: 'match' as const,
    belowColor: '#334155',
    belowPrefixShow: true,
    belowPrefixFontSize: 0,
    belowPrefixPosition: 'left' as const,
    belowPrefixVAlign: 'center' as const,
    belowPrefixPadding: 0,
    belowNumberFormat: { decimalPlaces: 2, thousandsSeparator: '.' as const, decimalSeparator: ',' as const, prefix: '', suffix: '', showTrailingZeros: true },
    namePosition: 'above' as const,
    nameFontFamily: 'Inter, sans-serif',
    nameFontSize: 22,
    nameFontWeight: 'bold' as const,
    nameBoldWeight: 'bold' as const,
    nameColorMode: 'match' as const,
    nameColor: '#334155',
    nameGap: 8,
    legendPosition: 'below' as const,
    legendOrientation: 'horizontal' as const,
    legendWidth: 170,
    legendDotSize: 10,
    legendDotGap: 6,
    legendFontSize: 14,
    legendFontWeight: 'bold' as const,
    legendColor: '#334155',
    legendAlign: 'left' as const,
    legendGap: 8,
    legendItemGapX: 16,
    legendItemGapY: 6,
    legendVisibleRows: {},
    diffShow: false,
    diffSource: 'info' as const,
    diffHeight: 44,
    diffBackgroundColor: '#fde8ec',
    diffCornerRadius: 0,
    diffMarginTop: 4,
    diffTemplate: '{leader} +{value}',
    diffMatchLeaderColor: true,
    diffColor: '#cc0033',
    diffFontFamily: 'Inter, sans-serif',
    diffFontSize: 22,
    diffFontWeight: 'bold' as const,
    diffFontStyle: 'normal' as const,
    diffUnderline: false,
    diffAlign: 'center' as const,
    diffNumberFormat: { decimalPlaces: 2, thousandsSeparator: '.' as const, decimalSeparator: ',' as const, prefix: '', suffix: '', showTrailingZeros: true },
    leftImage: { show: false, url: '', width: 110, height: 110, borderRadius: 10, position: 'side' as const, paddingTop: 0, paddingRight: 16, paddingBottom: 0, paddingLeft: 16, paddingX: 16, gap: 0 },
    rightImage: { show: false, url: '', width: 110, height: 110, borderRadius: 10, position: 'side' as const, paddingTop: 0, paddingRight: 16, paddingBottom: 0, paddingLeft: 16, paddingX: 16, gap: 0 },
    perSegment: {},
  },
  lineInfoAnnotation: {
    show: false,
    seriesA: '',
    seriesB: '',
    direction: 'right' as const,
    verticalLine: {
      show: true,
      style: 'dotted' as const,
      dotCount: 5,
      thickness: 1,
      color: '#cc0033',
      paddingTop: 4,
      paddingBottom: 4,
      topEndpoint: { type: 'none' as const, size: 6, color: '#999999' },
      bottomEndpoint: { type: 'none' as const, size: 6, color: '#999999' },
    },
    horizontalLine: {
      show: true,
      style: 'dotted' as const,
      dotCount: 5,
      thickness: 1,
      color: '#cc0033',
      endpoint: { type: 'circle_arrow' as const, size: 6, color: '#cc0033' },
    },
    text: {
      fontFamily: 'Inter, sans-serif',
      fontSize: 12,
      fontWeight: 'normal' as const,
      fontStyle: 'normal' as const,
      color: '#cc0033',
      letterSpacing: 0,
      textAlign: 'left' as const,
      paddingVertical: 2,
      paddingHorizontal: 4,
      dataType: 'text' as const,
    },
    perRowOverrides: {},
  },
  heatmap: {
    // Coloring
    colorMode: 'single' as const,
    baseColor: '#3b82f6',
    positiveColor: '#16a34a',
    negativeColor: '#dc2626',
    intensity: 0.65,
    includeTotalInScale: false,
    // Cells
    cellFontFamily: 'Inter, sans-serif',
    cellFontSize: 12,
    cellFontWeight: '500' as const,
    cellColor: '#1e293b',
    dashColor: '#4b5563',
    valueAlign: 'center' as const,
    density: 'normal' as const,
    zeroAsDash: true,
    showPercent: false,
    percentPosition: 'left' as const,
    percentFontSize: 12,
    striped: false,
    stripedColor: '#f8fafc',
    // Column header row
    headerBg: '#f1f5f9',
    headerFontFamily: 'Inter, sans-serif',
    headerFontSize: 11,
    headerFontWeight: '600' as const,
    headerColor: '#0f172a',
    headerUppercase: true,
    headerLetterSpacing: 0.4,
    headerAlign: 'center' as const,
    cornerLabel: '',
    // Row labels
    showRowDots: true,
    dotSize: 8,
    dotRadius: 2,
    labelFontFamily: 'Inter, sans-serif',
    labelFontSize: 12,
    labelFontWeight: '500' as const,
    labelColor: '#1e293b',
    labelAlign: 'left' as const,
    // Sizing
    sizingMode: 'auto' as const,
    wrapText: true,
    // Manual box dimensions (used in custom mode; 0 = auto)
    labelColWidth: 0,
    dataColWidth: 0,
    headerHeight: 0,
    rowHeight: 0,
    // Per-series overrides
    perColHeaderFontSizes: {},
    perColWidths: {},
    perColHeaderPadding: {},
    perRowLabelFontSizes: {},
    perRowHeights: {},
    perRowLabelPadding: {},
    // Borders
    borderShow: true,
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderStyle: 'solid' as const,
    // Totals
    showTotals: true,
    totalsMode: 'column' as const,
    totalLabel: 'Total',
    totalFontSize: 12,
    totalColor: '#1e293b',
    totalPercentFontSize: 12,
    totalCustomDecimals: false,
    totalDecimalPlaces: 0,
    // Outer
    cornerRadius: 12,
  },
  divergingBar: {
    seriesSides: {},
    scaleMode: 'independent' as const,
    centerGap: 0,
    absoluteValues: true,
    labelPosition: 'center' as const,
    legendCenterOnPlot: false,
    legendCenterGap: 0,
  },
};

export const defaultData = [
  { label: 'Australia', 'Series 1': 28, 'Series 2': 15, 'Series 3': 12 },
  { label: 'Brazil', 'Series 1': 22, 'Series 2': 18, 'Series 3': 25 },
  { label: 'Canada', 'Series 1': 35, 'Series 2': 20, 'Series 3': 8 },
  { label: 'France', 'Series 1': 18, 'Series 2': 30, 'Series 3': 16 },
  { label: 'Germany', 'Series 1': 42, 'Series 2': 12, 'Series 3': 22 },
  { label: 'India', 'Series 1': 15, 'Series 2': 35, 'Series 3': 28 },
  { label: 'Japan', 'Series 1': 30, 'Series 2': 25, 'Series 3': 18 },
];

export const defaultColumnMapping = {
  labels: 'label',
  values: ['Series 1', 'Series 2', 'Series 3'],
};
