import { ChartSettings } from '@/types/chart';

export const defaultChartSettings: ChartSettings = {
  chartType: {
    chartType: 'bar_stacked',
    stackSortMode: 'normal',
    gridMode: 'single',
    heightMode: 'auto',
    standardHeight: 400,
    aspectRatio: 16 / 9,
    aggregationMode: 'none',
    sortMode: 'data_sheet',
  },
  controlsFilters: {
    seriesFilter: 'off',
    maxSeriesToShow: 25,
    filterRowsNoData: false,
    controlPosition: 'top_left',
  },
  colors: {
    colorMode: 'by_column',
    palette: 'default',
    extend: true,
    customOverrides: '',
  },
  bars: {
    barHeight: 24,
    barOpacity: 1,
    spacingMain: 12,
    spacingInStack: 0,
    outline: false,
    outlineColor: '#ffffff',
    outlineWidth: 1,
  },
  labels: {
    barLabelStyle: 'axis',
    aboveBarPaddingTop: 0,
    aboveBarPaddingRight: 0,
    aboveBarPaddingBottom: 0,
    aboveBarPaddingLeft: 0,
    showDataPointLabels: false,
    dataPointFontSize: 12,
    dataPointFontFamily: 'Inter, sans-serif',
    dataPointFontWeight: 'normal',
    dataPointFontStyle: 'normal',
    dataPointColorMode: 'auto',
    dataPointColor: '#333333',
    dataPointSeriesColors: {},
    dataPointPosition: 'center',
    dataPointCustomPadding: false,
    dataPointPaddingTop: 0,
    dataPointPaddingRight: 0,
    dataPointPaddingBottom: 0,
    dataPointPaddingLeft: 0,
    stackLabelMode: 'none',
  },
  xAxis: {
    position: 'bottom',
    scaleType: 'linear',
    min: '',
    max: '',
    flipAxis: false,
    titleType: 'auto',
    titleText: '',
    titleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 12, fontWeight: 'normal', color: '#666666' },
    showTitleStyling: false,
    tickPosition: 'default',
    tickStyling: { fontFamily: 'Inter, sans-serif', fontSize: 11, fontWeight: 'normal', color: '#666666' },
    showTickStyling: false,
    tickPadding: 0,
    tickAngle: 0,
    ticksToShowMode: 'auto',
    ticksToShowNumber: 5,
    tickStep: 10,
    tickLabelCountMode: 'all',
    tickLabelCount: 0,
    hiddenTickLabels: [],
    lastLabelPadding: 0,
    tickMarks: { show: true, position: 'outside', length: 6, width: 1, color: '#666666' },
    axisLine: { show: true, width: 1, color: '#666666' },
    zeroLine: { show: true, width: 1, color: '#666666' },
    gridlines: true,
    gridlineStyling: { color: '#e5e5e5', width: 1, dashArray: 0 },
    showGridlineStyling: false,
  },
  yAxis: {
    position: 'left',
    scaleType: 'linear',
    min: '',
    max: '',
    titleType: 'auto',
    titleText: '',
    titleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 12, fontWeight: 'normal', color: '#666666' },
    showTitleStyling: false,
    tickPosition: 'default',
    tickStyling: { fontFamily: 'Inter, sans-serif', fontSize: 11, fontWeight: 'normal', color: '#666666' },
    showTickStyling: false,
    tickPadding: 0,
    spaceMode: 'auto',
    spaceModeValue: 120,
    axisLine: { show: true, width: 1, color: '#666666' },
    gridlines: false,
    gridlineStyling: { color: '#e5e5e5', width: 1, dashArray: 0 },
    showGridlineStyling: false,
  },
  plotBackground: {
    backgroundColor: '#ffffff',
    border: false,
    borderColor: '#cccccc',
    borderWidth: 1,
  },
  numberFormatting: {
    decimalPlaces: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    prefix: '',
    suffix: '',
  },
  legend: {
    show: true,
    clickToFilter: 'off',
    alignment: 'inline',
    titleWeight: 'bold',
    textWeight: 'normal',
    textStyle: 'normal',
    fontFamily: 'Inter, sans-serif',
    color: '#333333',
    size: 12,
    marginTop: 0,
    titleText: '',
    swatchWidth: 15,
    swatchHeight: 15,
    swatchRoundness: 0,
    swatchPadding: 6,
    outline: false,
    customOrder: '',
    maxWidth: 100,
    orientation: 'horizontal',
    position: 'below',
    overlayX: 10,
    overlayY: 10,
    dataColorsHeader: 'auto',
  },
  popupsPanels: {
    showPopup: true,
    popupContent: '{{column_name}}: {{value}}',
    popupStyle: 'light',
  },
  annotations: {
    annotations: [],
  },
  animations: {
    enabled: true,
    duration: 800,
    type: 'gradual',
  },
  layout: {
    maxWidth: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    backgroundColor: '#ffffff',
    backgroundOpacity: 100,
  },
  header: {
    alignment: 'left',
    title: '',
    titleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 22, fontWeight: 'bold', color: '#333333', lineHeight: 1.3 },
    subtitle: '',
    subtitleStyling: { fontFamily: 'Inter, sans-serif', fontSize: 16, fontWeight: 'normal', color: '#666666', lineHeight: 1.4 },
    text: '',
    textStyling: { fontFamily: 'Inter, sans-serif', fontSize: 14, fontWeight: 'normal', color: '#888888', lineHeight: 1.4 },
    border: 'none',
  },
  footer: {
    alignment: 'left',
    size: 11,
    color: '#888888',
    advancedStyles: false,
    sourceName: '',
    sourceUrl: '',
    multipleSources: false,
    sourceLabel: 'Source',
    notePrimary: '',
    noteSecondary: '',
    logoUrl: '',
    border: 'none',
  },
  accessibility: {
    alternativeDescription: '',
    altText: '',
  },
};

export const defaultData = [
  { label: 'Australia', 'Series 1': 28, 'Series 2': 15, 'Series 3': 12 },
  { label: 'Brazil', 'Series 1': 22, 'Series 2': 18, 'Series 3': 25 },
  { label: 'Canada', 'Series 1': 35, 'Series 2': 20, 'Series 3': 8 },
  { label: 'France', 'Series 1': 18, 'Series 2': 30, 'Series 3': 16 },
  { label: 'Germany', 'Series 1': 42, 'Series 2': 12, 'Series 3': 22 },
  { label: 'India', 'Series 1': 15, 'Series 2': 35, 'Series 3': 28 },
  { label: 'Japan', 'Series 1': 30, 'Series 2': 25, 'Series 3': 18 },
];

export const defaultColumnMapping = {
  labels: 'label',
  values: ['Series 1', 'Series 2', 'Series 3'],
};
